id: P004250
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-17 11:04:45.451314
source_metadata:
  id: bdr:W1KG18571
  title: མའོ་ཙེ་ཏུང་གི་གཏམ་རྒྱུད།
  author: ''
  volumes:
    e86fa436ea0444258abb8ac5ae0f1ca0:
      image_group_id: I1KG18659
      title: ''
      volume_number: 1
      total_pages: 126
      base_file: v001.txt
    10be9c4e911944ae8f0945a3e6f628fb:
      image_group_id: I1KG18660
      title: ''
      volume_number: 2
      total_pages: 132
      base_file: v002.txt
    9c890ac262e148eda396688528f3a524:
      image_group_id: I1KG18661
      title: ''
      volume_number: 3
      total_pages: 134
      base_file: v003.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
