id: P004250
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG18571
  title: མའོ་ཙེ་ཏུང་གི་གཏམ་རྒྱུད།
  author: ''
  volumes:
    e86fa436ea0444258abb8ac5ae0f1ca0:
      image_group_id: I1KG18659
      title: ''
      volume_number: 1
      total_pages: 126
    10be9c4e911944ae8f0945a3e6f628fb:
      image_group_id: I1KG18660
      title: ''
      volume_number: 2
      total_pages: 132
    9c890ac262e148eda396688528f3a524:
      image_group_id: I1KG18661
      title: ''
      volume_number: 3
      total_pages: 134
