id: IFE946CBF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T22:36:30+00:00'
last_modified: '2022-06-07T21:24:46.243951+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG18571
  title: མའོ་ཙེ་ཏུང་གི་གཏམ་རྒྱུད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    655B:
      image_group_id: I1KG18659
      title: ''
      total_pages: 126
      order: 1
      base_file: 655B.txt
    0DB3:
      image_group_id: I1KG18660
      title: ''
      total_pages: 132
      order: 2
      base_file: 0DB3.txt
    6F46:
      image_group_id: I1KG18661
      title: ''
      total_pages: 134
      order: 3
      base_file: 6F46.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
